[theme]
primaryColor = "#ffffffff"
backgroundColor = "#292929ff"
secondaryBackgroundColor = "#19191aff"
textColor = "#F8FAFC"
font = "sans serif"

[client]
showErrorDetails = true

[logger]
level = "info"

